env: "dev"
app-name: "Trening"
storage_path_dev:
  POSTGRES_PASSWORD: "123456"
  POSTGRES_HOST: "db"
  POSTGRES_USER: "admin"
  POSTGRES_DB: "trenings"
  POSTGRES_PORT: "5432"

storage_path:
  POSTGRES_PASSWORD: "123456"
  POSTGRES_HOST: "db"
  POSTGRES_USER: "admin"
  POSTGRES_DB: "trenings"
  POSTGRES_PORT: "5432"
grpc:
  port: 44044
  timeout: 1h

secret: "add"
tokenTTL: 1h