version: "3"

services:
  db:
    image: postgres:17
    container_name: db
    volumes:
      - ./database/:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "TRENINGS"
    ports:
      - "5432:5432"
    networks:
      - postgres

  trening_mc:
    build: ..
    container_name: trening_mc
    depends_on:
      - db
    restart: always
    networks:
      - postgres
    environment:
      - CONFIG_PATH=./ci/dev.yaml
    ports:
      - "8002:44044"


networks:
  postgres:
    driver: bridge
