version: "3.8"

services:
  db:
    image: postgres:17
    container_name: db
    volumes:
      - ./database/:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "TRENINGS"
    ports:
      - "5432:5432"
    networks:
      - postgres

  trening_mc:
    build: ..
    container_name: trening_mc
    depends_on:
      - db
      - tarantool
    volumes:
      - ../:/app
    networks:
      - postgres
    environment:
      - CONFIG_PATH=./ci/dev.yaml
      - AIR_ENV=development
    ports:
      - "8002:44044"
#      - "2345:2345"
    command:
      - air
#      - dlv exec /app/myapp --headless --listen=:2345 --api-version=2 --accept-multiclient

  tarantool:
    container_name: tarantool_trening
    image: tarantool/tarantool
    ports:
      - "3301:3301"
    networks:
      - postgres
    volumes:
      - ./tarantool/init.lua:/opt/tarantool/init.lua  # Монтируем скрипт в контейнер
      - tarantool_data:/var/lib/tarantool
    environment:
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "password"
      TARANTOOL_HOST: tarantool
      TARANTOOL_PORT: 3301
    command: tarantool /opt/tarantool/init.lua

volumes:
  tarantool_data:

networks:
  postgres:
    driver: bridge
